train:
  _target_: src.datasets.DigiCamRealDataset
  parquet_path: data/hf/DigiCam-Mirflickr-MultiMask-1K/data/train-00000-of-00001.parquet
  split: train
  indices: 170
  index_start: 0
  cache_dir: ${oc.env:HF_HOME,./data/huggingface}
  force_rgb: true
  rotate_measurement: true
  measurement_downsample: 1.0
  target_size: [200, 266]

validation:
  _target_: src.datasets.DigiCamRealDataset
  parquet_path: data/hf/DigiCam-Mirflickr-MultiMask-1K/data/train-00000-of-00001.parquet
  split: train
  indices: 85
  index_start: 170
  cache_dir: ${oc.env:HF_HOME,./data/huggingface}
  force_rgb: true
  rotate_measurement: true
  measurement_downsample: 1.0
  target_size: [200, 266]
