device: "auto"

train:
  - _target_: src.metrics.PSNRMetric
    data_range: 1.0
    normalize_by_max: true
    normalization_eps: 1.0e-8
    name: "PSNR"
  - _target_: src.metrics.SSIMMetric
    data_range: 1.0
    normalize_by_max: true
    normalization_eps: 1.0e-8
    name: "SSIM"

inference:
  - _target_: src.metrics.PSNRMetric
    data_range: 1.0
    normalize_by_max: true
    normalization_eps: 1.0e-8
    name: "PSNR"
  - _target_: src.metrics.SSIMMetric
    data_range: 1.0
    normalize_by_max: true
    normalization_eps: 1.0e-8
    name: "SSIM"
  - _target_: src.metrics.LPIPSMetric
    net_type: "vgg"
    device: ${metrics.device}
    normalize_by_max: true
    normalization_eps: 1.0e-8
    name: "LPIPS"
