input_dir: "../../synth_in"
save_dir: "../../synth_out"
generate_samples: true
extensions:
  - jpg
  - jpeg
dtype: float32
use_torch: true
torch_device: cpu
samples_per_mask: 5
n_psf: 5
synth_dataset: false
seed_base: 0
grayscale: false

pattern:
  shape: [54, 26]
  dist_type: uniform
  min_val: 0.0
  max_val: 1.0
  bernoulli_p: 0.5
  gaussian_std: 0.25

optics:
  sensor: rpi_hq
  slm: adafruit
  downsample: 8
  object_height:
    - 0.2
    - 0.8

  use_rotate: true
  rotate_min: -3.0
  rotate_max: 3.0

  use_vertical_shift: true
  vertical_shift_min: -30
  vertical_shift_max: 30

  use_horizontal_shift: true
  horizontal_shift_min: -30
  horizontal_shift_max: 30

  flipud: true
  deadspace: true
  use_waveprop: true

  scene2mask_min: 0.28
  scene2mask_max: 0.32

  mask2sensor_min: 0.0019
  mask2sensor_max: 0.0021

  min_val: 0.0
  snr_db: 0.0


