defaults:
  - e02_mask_scaling_screen
  - override model: psf_free_drunet_large
  - _self_

initialization_name: large-scratch

model:
  checkpoint_path: null

writer:
  run_name: pt-dpir-screen-${initialization_name}-${condition_name}-seed${trainer.seed}
  group: pretrain-pt-dpir-01
  job_type: ${initialization_name}
  tags: [synthetic, psf-free, article-resolution, pretrain, dpir, screen]

hydra:
  run:
    dir: outputs/train/pt-dpir-screen/${initialization_name}/${condition_name}/seed${trainer.seed}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: outputs/train/pt-dpir-screen/multirun/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${initialization_name}/${condition_name}/seed${trainer.seed}
